<?xml version="1.0" encoding="utf-8"?><Database Name="redirector" Class="RedirectDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.209.8.200;Initial Catalog=redirector;Persist Security Info=True;User ID=SQL_Redirector" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="redirectorConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Redirect" Member="Redirects">
    <Type Name="Redirect">
      <Column Name="base" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="redirect" Member="redirect1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>