#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redirector.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="redirector")]
	public partial class RedirectDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public RedirectDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["redirectorConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RedirectDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RedirectDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RedirectDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RedirectDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Redirect> Redirects
		{
			get
			{
				return this.GetTable<Redirect>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Redirect")]
	public partial class Redirect
	{
		
		private string _base;
		
		private string _redirect1;
		
		public Redirect()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="base", Storage="_base", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string @base
		{
			get
			{
				return this._base;
			}
			set
			{
				if ((this._base != value))
				{
					this._base = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="redirect", Storage="_redirect1", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string redirect1
		{
			get
			{
				return this._redirect1;
			}
			set
			{
				if ((this._redirect1 != value))
				{
					this._redirect1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
